
spring:
  zipkin:
    base-url: http://192.168.2.37:9411/ # zipkin 服务器的地址
    # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%
  cloud:
    gateway:
      routes:
#        - id: test
#          uri: https://www.baidu.com
#          predicates:
#           - Query=url,baidu
#
#        - id: qq
#          uri: https://www.qq.com
#          predicates:
#           - Query=url,qq
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*) ,/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*) ,/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*) ,/$\{segment}

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*) ,/$\{segment}

        - id : third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*) ,/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*) ,/renren-fast/$\{segment}

        - id: host_route
          uri: lb://mall-product
          predicates:
              - Host=mall.com

        - id: search_host_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: item_host_route
          uri: lb://mall-product
          predicates:
            - Host=item.mall.com

        - id: auth_host_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: cart_host_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com

        - id: order_host_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com

        - id: member_host_route
          uri: lb://mall-member
          predicates:
            - Host=member.mall.com
        - id: seckill_host_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.mall.com


logging:
  level:
    com.ly.gateway: debug
    com:
      alibaba:
        nacos:
          client:
            naming: OFF


## 前端项目 带上api