spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t8WBDyqtzjnT5Keopb9
      secret-key: tyUOlf96tUoCl1v3uRiaSdMUwqiToB
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-rshs
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        appcode: be3d963674fb40c383aeeecb80397cb0

  application:
    name: mall-third-party
  zipkin:
    base-url: http://192.168.2.37:9411/ # zipkin 服务器的地址
    # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%
server:
  port: 30000



